<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <Nullable>disable</Nullable>
  </PropertyGroup>

   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
     <NoWarn>;CS8321;CS1591</NoWarn>
   </PropertyGroup>

   <ItemGroup>
     <Folder Include="Properties\" />
   </ItemGroup>

   <ItemGroup>
     <PackageReference Include="FluentAssertions" Version="6.12.1" />
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
     <PackageReference Include="Moq" Version="4.20.72" />
     <PackageReference Include="NUnit" Version="4.2.2" />
     <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
   </ItemGroup>

   <ItemGroup>
     <ProjectReference Include="..\Wordclock.Core\Wordclock.Core.csproj" />
   </ItemGroup>

</Project>
