//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Wordclock.WSRenderEngine.RenderService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Application", Namespace="tns")]
    public partial class Application : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback disposeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNumberOfLEDsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPixelColorOperationCompleted;
        
        private System.Threading.SendOrPostCallback initializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback setBrightnessOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPixelAndRenderOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPixelColorOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPixelColorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback showOperationCompleted;
        
        private System.Threading.SendOrPostCallback shutdownOperationCompleted;
        
        private System.Threading.SendOrPostCallback testServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Application() {
            this.Url = global::Wordclock.WSRenderEngine.Properties.Settings.Default.WSRenderEngine_RenderService_Application;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event disposeCompletedEventHandler disposeCompleted;
        
        /// <remarks/>
        public event getNumberOfLEDsCompletedEventHandler getNumberOfLEDsCompleted;
        
        /// <remarks/>
        public event getPixelColorCompletedEventHandler getPixelColorCompleted;
        
        /// <remarks/>
        public event initializeCompletedEventHandler initializeCompleted;
        
        /// <remarks/>
        public event setBrightnessCompletedEventHandler setBrightnessCompleted;
        
        /// <remarks/>
        public event setPixelAndRenderCompletedEventHandler setPixelAndRenderCompleted;
        
        /// <remarks/>
        public event setPixelColorCompletedEventHandler setPixelColorCompleted;
        
        /// <remarks/>
        public event setPixelColorsCompletedEventHandler setPixelColorsCompleted;
        
        /// <remarks/>
        public event showCompletedEventHandler showCompleted;
        
        /// <remarks/>
        public event shutdownCompletedEventHandler shutdownCompleted;
        
        /// <remarks/>
        public event testServiceCompletedEventHandler testServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("dispose", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("disposeResponse", Namespace="tns")]
        public disposeResponse dispose([System.Xml.Serialization.XmlElementAttribute("dispose", Namespace="tns")] dispose dispose1) {
            object[] results = this.Invoke("dispose", new object[] {
                        dispose1});
            return ((disposeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void disposeAsync(dispose dispose1) {
            this.disposeAsync(dispose1, null);
        }
        
        /// <remarks/>
        public void disposeAsync(dispose dispose1, object userState) {
            if ((this.disposeOperationCompleted == null)) {
                this.disposeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisposeOperationCompleted);
            }
            this.InvokeAsync("dispose", new object[] {
                        dispose1}, this.disposeOperationCompleted, userState);
        }
        
        private void OndisposeOperationCompleted(object arg) {
            if ((this.disposeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.disposeCompleted(this, new disposeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getNumberOfLEDs", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getNumberOfLEDsResponse", Namespace="tns")]
        public getNumberOfLEDsResponse getNumberOfLEDs([System.Xml.Serialization.XmlElementAttribute("getNumberOfLEDs", Namespace="tns")] getNumberOfLEDs getNumberOfLEDs1) {
            object[] results = this.Invoke("getNumberOfLEDs", new object[] {
                        getNumberOfLEDs1});
            return ((getNumberOfLEDsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getNumberOfLEDsAsync(getNumberOfLEDs getNumberOfLEDs1) {
            this.getNumberOfLEDsAsync(getNumberOfLEDs1, null);
        }
        
        /// <remarks/>
        public void getNumberOfLEDsAsync(getNumberOfLEDs getNumberOfLEDs1, object userState) {
            if ((this.getNumberOfLEDsOperationCompleted == null)) {
                this.getNumberOfLEDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNumberOfLEDsOperationCompleted);
            }
            this.InvokeAsync("getNumberOfLEDs", new object[] {
                        getNumberOfLEDs1}, this.getNumberOfLEDsOperationCompleted, userState);
        }
        
        private void OngetNumberOfLEDsOperationCompleted(object arg) {
            if ((this.getNumberOfLEDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNumberOfLEDsCompleted(this, new getNumberOfLEDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getPixelColor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPixelColorResponse", Namespace="tns")]
        public getPixelColorResponse getPixelColor([System.Xml.Serialization.XmlElementAttribute("getPixelColor", Namespace="tns")] getPixelColor getPixelColor1) {
            object[] results = this.Invoke("getPixelColor", new object[] {
                        getPixelColor1});
            return ((getPixelColorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getPixelColorAsync(getPixelColor getPixelColor1) {
            this.getPixelColorAsync(getPixelColor1, null);
        }
        
        /// <remarks/>
        public void getPixelColorAsync(getPixelColor getPixelColor1, object userState) {
            if ((this.getPixelColorOperationCompleted == null)) {
                this.getPixelColorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPixelColorOperationCompleted);
            }
            this.InvokeAsync("getPixelColor", new object[] {
                        getPixelColor1}, this.getPixelColorOperationCompleted, userState);
        }
        
        private void OngetPixelColorOperationCompleted(object arg) {
            if ((this.getPixelColorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPixelColorCompleted(this, new getPixelColorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("initialize", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("initializeResponse", Namespace="tns")]
        public initializeResponse initialize([System.Xml.Serialization.XmlElementAttribute("initialize", Namespace="tns")] initialize initialize1) {
            object[] results = this.Invoke("initialize", new object[] {
                        initialize1});
            return ((initializeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void initializeAsync(initialize initialize1) {
            this.initializeAsync(initialize1, null);
        }
        
        /// <remarks/>
        public void initializeAsync(initialize initialize1, object userState) {
            if ((this.initializeOperationCompleted == null)) {
                this.initializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitializeOperationCompleted);
            }
            this.InvokeAsync("initialize", new object[] {
                        initialize1}, this.initializeOperationCompleted, userState);
        }
        
        private void OninitializeOperationCompleted(object arg) {
            if ((this.initializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initializeCompleted(this, new initializeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("setBrightness", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setBrightnessResponse", Namespace="tns")]
        public setBrightnessResponse setBrightness([System.Xml.Serialization.XmlElementAttribute("setBrightness", Namespace="tns")] setBrightness setBrightness1) {
            object[] results = this.Invoke("setBrightness", new object[] {
                        setBrightness1});
            return ((setBrightnessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setBrightnessAsync(setBrightness setBrightness1) {
            this.setBrightnessAsync(setBrightness1, null);
        }
        
        /// <remarks/>
        public void setBrightnessAsync(setBrightness setBrightness1, object userState) {
            if ((this.setBrightnessOperationCompleted == null)) {
                this.setBrightnessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetBrightnessOperationCompleted);
            }
            this.InvokeAsync("setBrightness", new object[] {
                        setBrightness1}, this.setBrightnessOperationCompleted, userState);
        }
        
        private void OnsetBrightnessOperationCompleted(object arg) {
            if ((this.setBrightnessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setBrightnessCompleted(this, new setBrightnessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("setPixelAndRender", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setPixelAndRenderResponse", Namespace="tns")]
        public setPixelAndRenderResponse setPixelAndRender([System.Xml.Serialization.XmlElementAttribute("setPixelAndRender", Namespace="tns")] setPixelAndRender setPixelAndRender1) {
            object[] results = this.Invoke("setPixelAndRender", new object[] {
                        setPixelAndRender1});
            return ((setPixelAndRenderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setPixelAndRenderAsync(setPixelAndRender setPixelAndRender1) {
            this.setPixelAndRenderAsync(setPixelAndRender1, null);
        }
        
        /// <remarks/>
        public void setPixelAndRenderAsync(setPixelAndRender setPixelAndRender1, object userState) {
            if ((this.setPixelAndRenderOperationCompleted == null)) {
                this.setPixelAndRenderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPixelAndRenderOperationCompleted);
            }
            this.InvokeAsync("setPixelAndRender", new object[] {
                        setPixelAndRender1}, this.setPixelAndRenderOperationCompleted, userState);
        }
        
        private void OnsetPixelAndRenderOperationCompleted(object arg) {
            if ((this.setPixelAndRenderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPixelAndRenderCompleted(this, new setPixelAndRenderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("setPixelColor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setPixelColorResponse", Namespace="tns")]
        public setPixelColorResponse setPixelColor([System.Xml.Serialization.XmlElementAttribute("setPixelColor", Namespace="tns")] setPixelColor setPixelColor1) {
            object[] results = this.Invoke("setPixelColor", new object[] {
                        setPixelColor1});
            return ((setPixelColorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setPixelColorAsync(setPixelColor setPixelColor1) {
            this.setPixelColorAsync(setPixelColor1, null);
        }
        
        /// <remarks/>
        public void setPixelColorAsync(setPixelColor setPixelColor1, object userState) {
            if ((this.setPixelColorOperationCompleted == null)) {
                this.setPixelColorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPixelColorOperationCompleted);
            }
            this.InvokeAsync("setPixelColor", new object[] {
                        setPixelColor1}, this.setPixelColorOperationCompleted, userState);
        }
        
        private void OnsetPixelColorOperationCompleted(object arg) {
            if ((this.setPixelColorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPixelColorCompleted(this, new setPixelColorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("setPixelColors", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setPixelColorsResponse", Namespace="tns")]
        public setPixelColorsResponse setPixelColors([System.Xml.Serialization.XmlElementAttribute("setPixelColors", Namespace="tns")] setPixelColors setPixelColors1) {
            object[] results = this.Invoke("setPixelColors", new object[] {
                        setPixelColors1});
            return ((setPixelColorsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setPixelColorsAsync(setPixelColors setPixelColors1) {
            this.setPixelColorsAsync(setPixelColors1, null);
        }
        
        /// <remarks/>
        public void setPixelColorsAsync(setPixelColors setPixelColors1, object userState) {
            if ((this.setPixelColorsOperationCompleted == null)) {
                this.setPixelColorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPixelColorsOperationCompleted);
            }
            this.InvokeAsync("setPixelColors", new object[] {
                        setPixelColors1}, this.setPixelColorsOperationCompleted, userState);
        }
        
        private void OnsetPixelColorsOperationCompleted(object arg) {
            if ((this.setPixelColorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPixelColorsCompleted(this, new setPixelColorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("show", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("showResponse", Namespace="tns")]
        public showResponse show([System.Xml.Serialization.XmlElementAttribute("show", Namespace="tns")] show show1) {
            object[] results = this.Invoke("show", new object[] {
                        show1});
            return ((showResponse)(results[0]));
        }
        
        /// <remarks/>
        public void showAsync(show show1) {
            this.showAsync(show1, null);
        }
        
        /// <remarks/>
        public void showAsync(show show1, object userState) {
            if ((this.showOperationCompleted == null)) {
                this.showOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowOperationCompleted);
            }
            this.InvokeAsync("show", new object[] {
                        show1}, this.showOperationCompleted, userState);
        }
        
        private void OnshowOperationCompleted(object arg) {
            if ((this.showCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showCompleted(this, new showCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("shutdown", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("shutdownResponse", Namespace="tns")]
        public shutdownResponse shutdown([System.Xml.Serialization.XmlElementAttribute("shutdown", Namespace="tns")] shutdown shutdown1) {
            object[] results = this.Invoke("shutdown", new object[] {
                        shutdown1});
            return ((shutdownResponse)(results[0]));
        }
        
        /// <remarks/>
        public void shutdownAsync(shutdown shutdown1) {
            this.shutdownAsync(shutdown1, null);
        }
        
        /// <remarks/>
        public void shutdownAsync(shutdown shutdown1, object userState) {
            if ((this.shutdownOperationCompleted == null)) {
                this.shutdownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshutdownOperationCompleted);
            }
            this.InvokeAsync("shutdown", new object[] {
                        shutdown1}, this.shutdownOperationCompleted, userState);
        }
        
        private void OnshutdownOperationCompleted(object arg) {
            if ((this.shutdownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shutdownCompleted(this, new shutdownCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("testService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("testServiceResponse", Namespace="tns")]
        public testServiceResponse testService([System.Xml.Serialization.XmlElementAttribute("testService", Namespace="tns")] testService testService1) {
            object[] results = this.Invoke("testService", new object[] {
                        testService1});
            return ((testServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void testServiceAsync(testService testService1) {
            this.testServiceAsync(testService1, null);
        }
        
        /// <remarks/>
        public void testServiceAsync(testService testService1, object userState) {
            if ((this.testServiceOperationCompleted == null)) {
                this.testServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestServiceOperationCompleted);
            }
            this.InvokeAsync("testService", new object[] {
                        testService1}, this.testServiceOperationCompleted, userState);
        }
        
        private void OntestServiceOperationCompleted(object arg) {
            if ((this.testServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testServiceCompleted(this, new testServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class dispose {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class testServiceResponse {
        
        private string testServiceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testServiceResult {
            get {
                return this.testServiceResultField;
            }
            set {
                this.testServiceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class testService {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class shutdownResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class shutdown {
        
        private string abField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ab {
            get {
                return this.abField;
            }
            set {
                this.abField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class showResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class show {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setPixelColorsResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setPixelColors {
        
        private string idsField;
        
        private string redField;
        
        private string greenField;
        
        private string blueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string red {
            get {
                return this.redField;
            }
            set {
                this.redField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string green {
            get {
                return this.greenField;
            }
            set {
                this.greenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string blue {
            get {
                return this.blueField;
            }
            set {
                this.blueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setPixelColorResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setPixelColor {
        
        private string ledIDField;
        
        private string redField;
        
        private string greenField;
        
        private string blueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledID {
            get {
                return this.ledIDField;
            }
            set {
                this.ledIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string red {
            get {
                return this.redField;
            }
            set {
                this.redField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string green {
            get {
                return this.greenField;
            }
            set {
                this.greenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string blue {
            get {
                return this.blueField;
            }
            set {
                this.blueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setPixelAndRenderResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setPixelAndRender {
        
        private string renderStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string renderString {
            get {
                return this.renderStringField;
            }
            set {
                this.renderStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setBrightnessResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class setBrightness {
        
        private string brightnessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string brightness {
            get {
                return this.brightnessField;
            }
            set {
                this.brightnessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class initializeResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class initialize {
        
        private string ledCountField;
        
        private string ledPinField;
        
        private string ledFrequenceField;
        
        private string ledDMAField;
        
        private System.Nullable<bool> ledInvertField;
        
        private bool ledInvertFieldSpecified;
        
        private string ledBrightnessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledCount {
            get {
                return this.ledCountField;
            }
            set {
                this.ledCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledPin {
            get {
                return this.ledPinField;
            }
            set {
                this.ledPinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledFrequence {
            get {
                return this.ledFrequenceField;
            }
            set {
                this.ledFrequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledDMA {
            get {
                return this.ledDMAField;
            }
            set {
                this.ledDMAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ledInvert {
            get {
                return this.ledInvertField;
            }
            set {
                this.ledInvertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ledInvertSpecified {
            get {
                return this.ledInvertFieldSpecified;
            }
            set {
                this.ledInvertFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledBrightness {
            get {
                return this.ledBrightnessField;
            }
            set {
                this.ledBrightnessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class getPixelColorResponse {
        
        private string getPixelColorResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string getPixelColorResult {
            get {
                return this.getPixelColorResultField;
            }
            set {
                this.getPixelColorResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class getPixelColor {
        
        private string ledIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string ledID {
            get {
                return this.ledIDField;
            }
            set {
                this.ledIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class getNumberOfLEDsResponse {
        
        private string getNumberOfLEDsResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string getNumberOfLEDsResult {
            get {
                return this.getNumberOfLEDsResultField;
            }
            set {
                this.getNumberOfLEDsResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class getNumberOfLEDs {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class disposeResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void disposeCompletedEventHandler(object sender, disposeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class disposeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal disposeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public disposeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((disposeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNumberOfLEDsCompletedEventHandler(object sender, getNumberOfLEDsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNumberOfLEDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNumberOfLEDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getNumberOfLEDsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getNumberOfLEDsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getPixelColorCompletedEventHandler(object sender, getPixelColorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPixelColorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPixelColorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getPixelColorResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getPixelColorResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void initializeCompletedEventHandler(object sender, initializeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public initializeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((initializeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setBrightnessCompletedEventHandler(object sender, setBrightnessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setBrightnessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setBrightnessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setBrightnessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setBrightnessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setPixelAndRenderCompletedEventHandler(object sender, setPixelAndRenderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPixelAndRenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPixelAndRenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setPixelAndRenderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setPixelAndRenderResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setPixelColorCompletedEventHandler(object sender, setPixelColorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPixelColorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPixelColorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setPixelColorResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setPixelColorResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setPixelColorsCompletedEventHandler(object sender, setPixelColorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPixelColorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPixelColorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setPixelColorsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setPixelColorsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void showCompletedEventHandler(object sender, showCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public showResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((showResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void shutdownCompletedEventHandler(object sender, shutdownCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shutdownCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shutdownCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public shutdownResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((shutdownResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void testServiceCompletedEventHandler(object sender, testServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public testServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((testServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591